### PR TITLE
automatic extract script and style tags from html token content

### PR DESCRIPTION
**Pull request by rlsz**
Add ruler: automatic extract script and style tags from html token content.
Script will be excuted, and style will be added to ducument head.
No need to write script code and style code twice.
#2 --this issue could be avoided.

### CODE REVIEW

**Comment by huangshuwei** [comment]
I have already started using it.
it's really a good PR

**Comment by QingWei-Li** [comment]
Cool. I will test it tonight.

**Comment by rlsz** [comment]
Hold on.
I just found reg "<(script|style)[^<]*<\/\\1>" confused special chars '<' or "</script>" or "</style>".

**Comment by QingWei-Li** [comment]
`v2.0.0` is released.

**Pull request merged**
